name: Deploy To Prod

on:
    push:
        branches:
            - main
        paths:
            - 'force-app/**'

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-environment/deploy-prod-action